import Head from 'next/head';
import NavBar from '../components/NavBar';
import SideBar from '../components/SideBar';
import Feed from '../components/Feed';
import { useState } from 'react';
import TrendingPosts from '../components/TrendingPosts';
import CreatePost from '../components/CreatePost';

export default function Home() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [createPostOpen, setCreatePostOpen] = useState(false);

  const openCreatePost = () => {
    setCreatePostOpen(true);
  };

  const closeCreatePost = () => {
    setCreatePostOpen(false);
  };

  return (
    <div>
      <Head>
        <title>Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={` min-h-[100vh]  bg-[#f4f4f4] overflow-x-hidden `}>
        <NavBar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
        <SideBar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
        <div className=" mx-auto lg:flex lg:ml-16 justify-center xs:w-full md:max-w-[34rem] lg:max-w-[100%]  lg:mr-5 lg:mt-[5.5rem] mt-[3.5rem] md:mt-[4rem]">
          <div className="grid grid-cols-10 lg:w-[93%] xl:w-[75%] 2xl:w-[72.5rem] gap-8 ">
            <div className="col-span-10 lg:col-span-7  w-full outline-2">
              <Feed openCreatePost={openCreatePost} />
            </div>
            <div className="hidden lg:block lg:col-span-3 ">
              <TrendingPosts />
            </div>
          </div>
        </div>
        {createPostOpen && <CreatePost closeCreatePost={closeCreatePost} />}
      </main>
    </div>
  );
}
