import Head from 'next/head';
import NavBar from '../components/NavBar';
import SideBar from '../components/SideBar';
import { useState } from 'react';

export default function Home() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <div>
      <Head>
        <title>Nova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`h-[2000px] scrollbar-hide  bg-[#f4f4f4] overflow-x-hidden`}>
        <NavBar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
        <SideBar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
      </main>
    </div>
  );
}
